name: Check workflow running linter, unit and functional tests

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master, main]
    paths-ignore:
      - "**.md"
      - "**.rst"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  func:
    name: functional tests
    runs-on: ${{ matrix.architecture.runs-on }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        juju-channel: ["3.4/stable"]
        architecture:
          - runs-on: [self-hosted, jammy, X64, two-xlarge]
            mondel-constraints: ""
          # - runs-on: [self-hosted, jammy, ARM64, medium]
          #   model-constraints: arch=arm64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup juju environement
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: "lxd"
          juju-channel: ${{ matrix.juju-channel }}
          charmcraft-channel: "2.x/stable"
          bootstrap-constraints: "virt-type=virtual-machine"
      - name: Show juju information
        run: |
          juju version
          juju controllers | grep version -A 1 | awk '{print $9}'
      - name: Install latest tox version
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Run tests
        run: "make integration"
        env:
          TEST_MODEL_CONSTRAINTS: ${{ matrix.architecture.model-constraints }}
          TEST_JUJU3: "1"
      - name: Debug
        if: ${{ always() }}
        run: |
          juju models
          juju models | grep zaza | awk '{print $1}' | xargs -L 1 juju status
