name: Update files
on:
  workflow_dispatch:
  schedule:
    - cron: '43 1 * * 1'

jobs:

  pull-from-sunbeam:
    name: Pull files from sunbeam
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
        
      - name: Check pull from sunbeam
        run: make sync-dashboards-alert-rules

      - name: Create a PR for local changes
        uses: peter-evans/create-pull-request@v6
        id: cpr
        with:
          commit-message: "chore: update dashboards and alert rules"
          title: "chore: update dashboards and alert rules"
          body: |
            Automated action to fetch the latest grafana dashboards and alert rules from Sunbeam. The branch of this PR 
            will be overwritten during the next check. Unless you really know what you're doing, you 
            most likely don't want to push any commits to this branch.
          branch: chore/auto-libs
          delete-branch: true